# Generated by Django 2.1.3 on 2019-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caballo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota', models.FloatField(blank=True, max_length=4, null=True)),
                ('fechaAp', models.DateField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(choices=[('A', 'Activa'), ('G', 'Ganada'), ('P', 'Perdida'), ('D', 'Devuelta')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('montoD', models.FloatField(blank=True, max_length=10, null=True)),
                ('id_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuesta.Apuesta')),
                ('id_cab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caballo.Caballo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoApuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=70)),
                ('estatus', models.CharField(default='A', max_length=1)),
            ],
        ),
    ]
