# Generated by Django 2.1.3 on 2019-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jornada', '0001_initial'),
        ('monedavirtual', '0001_initial'),
        ('apuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuesta',
            name='idTrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_apuesta', to='monedavirtual.Transaccion'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='idTransGanada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_ganadora', to='monedavirtual.Transaccion'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='id_carr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jornada.Carrera'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='id_jorh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jornada.JornadaH'),
        ),
        migrations.AddField(
            model_name='apuesta',
            name='tApuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuesta.TipoApuesta'),
        ),
    ]
