# Generated by Django 2.1.3 on 2019-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jockey', '0001_initial'),
        ('hipodromo', '0001_initial'),
        ('caballo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('cant_caballos', models.IntegerField(null=True)),
                ('distancia', models.FloatField(max_length=4, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('a', 'Activa'), ('c', 'Corriendo'), ('f', 'Finalizada'), ('e', 'Eliminada'), ('p', 'Publicada')], default='a', max_length=1)),
                ('publicable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetallesCarrera',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('a', 'Activa'), ('r', 'Retirado')], default='a', max_length=1)),
                ('id_caba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caballo.Caballo')),
                ('id_carr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornada.Carrera')),
                ('id_jock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jockey.Jockey')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=20)),
                ('hora', models.TimeField(max_length=10)),
                ('estado', models.CharField(default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaH',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cant_carr', models.IntegerField()),
                ('fecha_reg', models.DateField(default=django.utils.timezone.now)),
                ('estatus', models.CharField(blank=True, choices=[('a', 'Activa'), ('e', 'Eliminada'), ('f', 'Finalizada')], default='a', max_length=1)),
                ('id_hip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipodromo.Hipodromo')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_jh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornada.JornadaH'),
        ),
    ]
